kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: mysecret
  creationTimestamp: null
spec:
  template:
    metadata:
      name: mysecret
      namespace: default
      creationTimestamp: null
    data: null
  encryptedData:
    foo: AgCEsFb5tOdepZzr3pReK80syMWUIMoWq+pVGeTxcO5w0L0KGYUxpEPMXfipbm5le+a3LTI8QCsibYR7KNMuGcCQGQ2A4DJ7ladmbYmzl3DD/U8pS/RFQcTXm3nQrFMAqtwPcD6byPzn7o4+bJUbkiRHjA92j8MYXw2msXGMDjO9gYMNDiNrD8yiPuXP/mGGkxMeF8XoP5vkJrHHWyLkdDE+RBACVAxyBPk5Gt1nVPXVsJh9p3EsZo0K2hytMEV7g9/E9qHebVi81uzDOmLK44buZpVY3twazGm/d3qODFy6kDU4R11OOZQdMC4a6Quw75x9tAb4RKnqhKjH13WYaJmNvkdciNUcZ+99HBUcGu0aEBj/qn9UBYZbizQIgulXVNBfyw5WBS9t4ks1FyobS30nvi4seQwpxQCZ1XfikCBHzVOafxFCkFIrUN5t+loCnM/Q7GCuyw7/eIw8R1EQs13dqP0FB8MxL+n30JOBFGiPGgzuHdad2EmQo9qj88Bsc+ZNmWeblKnQqy5iFdOIifkwUdW+zEvaUgV1hC+mUO14Ainm1DAmoJmAHsXbDtF4Hf8RVufq+8N0LpoVusNodkoiS7Mk+0xvrXpHZN+oYTN7Jok+tTux2VjqYKhAcdOlnPj/27woAYs4vhMisXWwSKhvhRkJA3r7ifMknFFE3/2lIRqoYQw0TsUloAAGvJRu11TKd4s=
